
package com.lcrc.af.gw.client.stubs.vdabapi.v7;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IVDABControlAPI", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", wsdlLocation = "http://localhost:8080/cc/ws/gw/acc/vdab/web/IVDABControlAPI?WSDL")
public class IVDABControlAPI
    extends Service
{

    private final static URL IVDABCONTROLAPI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lcrc.af.gw.client.stubs.vdabapi.v7.IVDABControlAPI.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lcrc.af.gw.client.stubs.vdabapi.v7.IVDABControlAPI.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/cc/ws/gw/acc/vdab/web/IVDABControlAPI?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/cc/ws/gw/acc/vdab/web/IVDABControlAPI?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IVDABCONTROLAPI_WSDL_LOCATION = url;
    }

    public IVDABControlAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IVDABControlAPI() {
        super(IVDABCONTROLAPI_WSDL_LOCATION, new QName("http://example.com/gw/acc/vdab/web/IVDABControlAPI", "IVDABControlAPI"));
    }

    /**
     * 
     * @return
     *     returns IVDABControlAPIPortType
     */
    @WebEndpoint(name = "IVDABControlAPISoap11Port")
    public IVDABControlAPIPortType getIVDABControlAPISoap11Port() {
        return super.getPort(new QName("http://example.com/gw/acc/vdab/web/IVDABControlAPI", "IVDABControlAPISoap11Port"), IVDABControlAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVDABControlAPIPortType
     */
    @WebEndpoint(name = "IVDABControlAPISoap11Port")
    public IVDABControlAPIPortType getIVDABControlAPISoap11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/gw/acc/vdab/web/IVDABControlAPI", "IVDABControlAPISoap11Port"), IVDABControlAPIPortType.class, features);
    }

}
