
package com.lcrc.af.gw.client.stubs.vdabapi.v7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IVDABControlAPIPortType", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVDABControlAPIPortType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
    @RequestWrapper(localName = "getAvailableObjects", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.GetAvailableObjects")
    @ResponseWrapper(localName = "getAvailableObjectsResponse", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.GetAvailableObjectsResponse")
    public String getAvailableObjects();

    /**
     * 
     * @param objName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
    @RequestWrapper(localName = "getAvailableCommands", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.GetAvailableCommands")
    @ResponseWrapper(localName = "getAvailableCommandsResponse", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.GetAvailableCommandsResponse")
    public String getAvailableCommands(
        @WebParam(name = "objName", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
        String objName);

    /**
     * 
     * @param cmd
     * @param objName
     * @param argStr
     * @param scopeStr
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
    @RequestWrapper(localName = "execute", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.ExecuteResponse")
    public int execute(
        @WebParam(name = "objName", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
        String objName,
        @WebParam(name = "cmd", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
        String cmd,
        @WebParam(name = "scopeStr", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
        String scopeStr,
        @WebParam(name = "argStr", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
        String argStr);

    /**
     * 
     * @param cmd
     * @param objName
     * @return
     *     returns com.lcrc.af.gw.client.stubs.vdabapi.v7.ControlUIInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
    @RequestWrapper(localName = "getCommandUIInfo", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.GetCommandUIInfo")
    @ResponseWrapper(localName = "getCommandUIInfoResponse", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI", className = "com.lcrc.af.gw.client.stubs.vdabapi.v7.GetCommandUIInfoResponse")
    public ControlUIInfo getCommandUIInfo(
        @WebParam(name = "objName", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
        String objName,
        @WebParam(name = "cmd", targetNamespace = "http://example.com/gw/acc/vdab/web/IVDABControlAPI")
        String cmd);

}
